/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      spacing: {
        1.5: '6px',
        20: `4.625rem`,
        15: '3.75rem',
        default: '10px',
      },
      height: {
        15: '3.75rem',
        top: '208px',
      },
      boxShadow: {
        sidebar: '0px 2px 10px rgba(196, 196, 196, 0.5)',
      },
    },
    fontSize: {
      xs: ['1.2rem'],
      sm: ['1.4rem'],
      base: ['1.6rem'],
      lg: ['1.8rem'],
      xl: ['2rem'],
      '2xl': ['2.2rem'],
      '3xl': ['2.4rem'],
      '4xl': ['2.6rem'],
      '5xl': ['2.8rem'],
      '6xl': ['3rem'],
      '7xl': ['3.2rem'],
      '8xl': ['3.4rem'],
      '9xl': ['3.6rem'],
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1440px',
    },
    fontFamily: {
      sans: `Pretendard, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", sans-serif;`,
      solano: `"Solano Gothic", sans-serif`,
    },
    colors: {
      transparent: 'transparent',
      white: '#fff',
      black: '#000',
      disable: '#e0e0e0',
      'primary-1': '#ff6d00',
      'primary-2': '#061138',
      'primary-3': '#ff862c',
      'primary-4': '#171C8F',
      'primary-5': '#FF4600',
      'success-1': '#2f80ed',
      'success-2': '#e3f5ff',
      'error-1': '#ef4747',
      'error-2': '#ffefef',
      'warning-1': '#ffd34d',
      'warning-2': '#fff7dd',
      'download-1': '#27ae60',
      'download-2': '#6fcf97',
      'download-3': '#e4fbf0',
      'typo-1': '#333',
      'typo-2': '#4f4f4f',
      'typo-3': '#828282',
      'typo-4': '#bdbdbd',
      'typo-5': '#e0e0e0',
      'typo-6': '#f2f2f2',
      'typo-7': '#f8f8f8',
      'p-blue-1': '#7da9ff',
      'p-blue-2': '#84b5ff',
      'p-blue-3': '#78cee9',
      'p-purple-1': '#a485ff',
      'p-purple-2': '#978eff',
      'p-green-1': '#90cca0',
      'p-green-2': '#98e6a9',
      'p-green-3': '#d6f5dd',
      'p-green-4': '#9dd764',
      'p-green-5': '#5bcbb7',
      'p-red-1': '#ff766d',
      'p-pink-1': '#ff92a5',
      'p-pink-2': '#ffcfec',
      'p-yellow-1': '#fde047',
      'p-yellow-2': '#ffd98e',
      'p-yellow-3': '#ffd34d',
      'p-brown-1': '#d3a064',
      'p-orange-1': '#ffab6c',
      'p-orange-2': '#ffd5b5',
      'other-1': '#5d5fef',
      'other-2': '#e5e6ff',
      currentColor: 'currentColor',
    },
  },
  plugins: [],
  experimental: {
    optimizeUniversalDefaults: true,
  },
};
